<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DocIntelligence.Worker-32ab7537-d8c3-4fa8-99d4-3c2ac44929cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.15" />
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocIntelligence.Application\DocIntelligence.Application.csproj" />
    <ProjectReference Include="..\DocIntelligence.Infrastructure\DocIntelligence.Infrastructure.csproj" />
  </ItemGroup>
</Project>
